### ISSUE TITLE
test out if https://nominatim.org/ is good geocoder.

### ISSUE THREAD

**Issue by ninyawee** [korkortorplus/ballot-location#1]
- [ ] 1% sample entries from https://docs.google.com/spreadsheets/d/19oosGgL5OC7Qdu5RwYDEkqQSsNgkThMS22pEKpz77qc/edit#gid=980581765
- [ ] test against public api(limit 1req/s) or spin own server
- [ ] make qualitative judgement

## Might Help
- [compose file](https://github.com/korkortorplus/ballot-location/blob/main/docker-compose.yml)

**Comment by wasdee** [comment]
> ผม มี deploy ใว้แล้ว เผื่อได้ใช้ครับ https://nominatim.vallarismaps.com/

**Comment by wasdee** [comment]
![image](https://github.com/korkortorplus/ballot-location/assets/8089231/2ba1bfd9-2c12-42c6-a312-31e93bea96ae)

เท่าที่ดูในด้าน query op น่าจะใช้ได้เฉพาะจังหวัด
สำคัญคือชื่อสถานที่ต้อง exact match เท่านั้น
เช่น 
ศาลาวัดหนองโสน 👎
วัดหนองโสน 👍

ผมคิดว่าจะต้อง clean data ดีมากๆ ก่อน ไม่ก็หาวิธี partial match

**Comment by wasdee** [comment]
ที่หักมุมคือ วัดหนองโสน ที่หาควรอยู่อยุธยา ไม่ใช่เพชรบูรณ์ สรุปแบบเร็วๆเดาๆ คือ geocoder osm น่าจะมีความน่าเชื่อถือที่ไว้ใจได้ 60% และครอบคลุม coverage 20% ของข้อมูล คือ 100k หน่วยอาจจะออก 20k แล้วก็ lat lng ถูก 12k หน่วย
